// export * from './minio/service';
export * from './FileUpload/file-upload.service';
export * from './qr-factory.service';
export * from './shopping-cart-service.service';
export * from './activity.service';
export * from './event.service';
export * from './address.service';
export * from './push-notification.service';
export * from './auth.service';
export * from './stripe.service';
