// export * from './minio/service';
export * from './activity/activity.service';
export * from './address.service';
export * from './auth.service';
export * from './event.service';
export * from './FileUpload/file-upload.service';
export * from './order.service';
export * from './push-notification.service';
export * from './qr-factory.service';
export * from './shopping-cart-service.service';
export * from './stripe.service';

export * from './email.service';
export * from './product.service';
export * from './spotify.service';
export * from './dev.service';
export * from './encryption.service';
export * from './staff-service.service';
export * from './manager-service.service';
export * from './stock-service.service';
